DROP DATABASE pointofsale;
CREATE DATABASE pointofsale;
USE pointofsale;
PRINT('CREATE Bill')
CREATE TABLE Bill(
	Id INT IDENTITY(1,1),
	Value MONEY NOT NULL,
	PRIMARY KEY(Id)
);
PRINT('CREATE COIN')
CREATE TABLE Coin(
	Id INT IDENTITY(1,1),
	Value MONEY NOT NULL,
	PRIMARY KEY(Id)
);
PRINT('CREATE Transactions');
CREATE TABLE Transactions(
	Id INT IDENTITY(1,1),
	ValueToPay MONEY NOT NULL,
	TotalValue MONEY NOT NULL,
	Change MONEY NOT NULL,
	ChangeMessage VARCHAR(255) NOT NULL,
	RegistrationDate  DATETIME DEFAULT GETDATE(),
	PRIMARY KEY(Id)
);

INSERT INTO Bill VALUES(100.0),(50.0),(20.0),(10.0);
INSERT INTO COIN VALUES(50.0),(10.0),(5.0),(1.0);