USE [master]
GO
CREATE DATABASE [pointofsale]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'pointofsale', FILENAME = N'/var/opt/mssql/data/pointofsale.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'pointofsale_log', FILENAME = N'/var/opt/mssql/data/pointofsale_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [pointofsale] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [pointofsale].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [pointofsale] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [pointofsale] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [pointofsale] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [pointofsale] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [pointofsale] SET ARITHABORT OFF 
GO
ALTER DATABASE [pointofsale] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [pointofsale] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [pointofsale] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [pointofsale] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [pointofsale] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [pointofsale] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [pointofsale] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [pointofsale] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [pointofsale] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [pointofsale] SET  ENABLE_BROKER 
GO
ALTER DATABASE [pointofsale] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [pointofsale] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [pointofsale] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [pointofsale] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [pointofsale] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [pointofsale] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [pointofsale] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [pointofsale] SET RECOVERY FULL 
GO
ALTER DATABASE [pointofsale] SET  MULTI_USER 
GO
ALTER DATABASE [pointofsale] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [pointofsale] SET DB_CHAINING OFF 
GO
ALTER DATABASE [pointofsale] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [pointofsale] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [pointofsale] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [pointofsale] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'pointofsale', N'ON'
GO
ALTER DATABASE [pointofsale] SET QUERY_STORE = OFF
GO
USE [pointofsale]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Bill](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Value] [money] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Coin](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Value] [money] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Transactions](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ValueToPay] [money] NOT NULL,
	[TotalValue] [money] NOT NULL,
	[Change] [money] NOT NULL,
	[ChangeMessage] [varchar](255) NOT NULL,
	[RegistrationDate] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Transactions] ADD  DEFAULT (getdate()) FOR [RegistrationDate]
GO
INSERT INTO Bill VALUES(100.0),(50.0),(20.0),(10.0);
INSERT INTO COIN VALUES(50.0),(10.0),(5.0),(1.0);
GO
USE [master]
GO
ALTER DATABASE [pointofsale] SET  READ_WRITE 
GO